<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounddesign');// Pour le texte ?>

<div class="wrap-footer" >
    <div id="footer" class="row">
		<div class="wrapper">
			<div class="logo">
	            <a href="<?php echo $this->url('frontend', array('channel' => $this->channel)) ?>">
	                <img src="<?php echo $this->frontendAssetPath('images/common/logo-white.png')?>" />
	            </a>
	        </div>
	        <ul class="footer-links">
	            <li>
	                <a href="<?php echo $this->url('frontend', array('channel' => $this->channel)) ?>"><?php echo $this->translate('Home'); ?></a>
	            </li>
	            <li>
	                <a href="<?php echo $this->url('frontend/contact', array('channel' => $this->channel)) ?>"><?php echo $this->translate('Contact us'); ?></a>
	            </li>
	            <li>
	                <a href="<?php echo $this->url('frontend/faq', array('channel' => $this->channel)) ?>"><?php echo $this->translate('FAQ'); ?></a>
	            </li>
	        </ul>
		</div>
    </div>
</div>
<div id="reglement-popin" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">
              Fermer
          </button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>